---

- name: include policy framework variables
  include_vars:
    file: "group_vars/policy-framework.yml"

- name: clear policy maps
  asa_config:
    lines:
      - "{{ item }}"
  when: override_policy_framework == true
  with_items:
    - "no service-policy {{ global_policy.0.name }} global"
    - "no policy-map {{ global_policy.0.name }}"
    - "no policy-map type inspect dns {{ dns_policy.0.name }}"
  ignore_errors: yes

- name: write dns policy map
  asa_config:
    parents: ['policy-map type inspect dns {{ dns_policy.0.name }}', 'parameters']
    lines:
      - "{{ item }}" 
  with_items:
    - "{{ dns_policy.0.lines }}"

- name: write policy-map global_policy
  asa_config:
    parents: ['policy-map {{ global_policy.0.name }}', 'class {{ global_policy.0.class }}']
    lines:
      - "{{ item }}"
  with_items:
    - "{{ global_policy.0.lines }}"
  register: result

- name: assign service policy
  asa_config:
    lines:
      - service-policy {{ global_policy.0.name }} global
  when: result.changed
